version: '3.4'
services:
  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - knocking_dev
    depends_on:
      - db
  db:
    image: postgres:alpine
    env_file:
      - ./backend/.env
    restart: always
    expose:
      - ${DB_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - knocking_dev

networks:
  knocking_dev:
    driver: bridge

volumes:
  db_data: {}
