name: Deploy to EC2

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Execute commands on remote server
        env:
          PRIVATE_KEY: ${{ secrets.SSH_BENEFIT }}
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
          SERVER_PATH: ${{ secrets.BACK_PATH }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $USERNAME@$HOST <<EOF
            cd $SERVER_PATH
            git pull
            docker-compose down
            docker-compose up -d
          EOF

          rm -f private_key.pem
